### ISSUE TITLE
Add Comcast to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#104]
Add logo and metadata for Comcast

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/comcast-member.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=comcast-member

**Comment by ninjaginja** [comment]
added in https://github.com/lf-edge-landscape/lfedge-landscape/pull/75
