### ISSUE TITLE
Add Mesosphere to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#159]
Add logo and metadata for Mesosphere

**Comment by bprestonlf** [comment]
https://drive.google.com/open?id=1W-i_iQ1BJHjHhfN3pmdtnGyJF10KKbku

**Comment by ninjaginja** [comment]
should this be updated to D2iQ?

**Comment by dankohn** [comment]
Yes.

**Comment by wesreisz** [comment]
[D2IQ.svg.zip](https://github.com/lf-edge-landscape/lfedge-landscape/files/3941719/D2IQ.svg.zip)

**Comment by wesreisz** [comment]
Adding...
