### ISSUE TITLE
Add Portworx to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#170]
Add logo and metadata for Portworx

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/portworx.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=portworx

**Comment by ninjaginja** [comment]
added #234
