### ISSUE TITLE
Add Project Calico to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#171]
Add logo and metadata for Project Calico

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/project-calico.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=project-calico

**Comment by ninjaginja** [comment]
closed in branch #256
