### ISSUE TITLE
Add Rafay to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#175]
Add logo and metadata for Rafay

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/rafay-systems-member.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=rafay-systems-member

**Comment by ninjaginja** [comment]
Tackling this one

**Comment by ninjaginja** [comment]
Added to landscape
