### ISSUE TITLE
Add StorageOS to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#186]
Add logo and metadata for StorageOS

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/storage-os-member.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=storage-os-member

**Comment by wesreisz** [comment]
merged
