### ISSUE TITLE
Add Telxius to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#192]
Add logo and metadata for Telxius

**Comment by aarondonwilliams** [comment]
[Telxius_logo.svg.zip](https://github.com/lf-edge-landscape/lfedge-landscape/files/4109833/Telxius_logo.svg.zip)

**Comment by aarondonwilliams** [comment]
cat- real estate- traditional
item:
            name: Telxius
            homepage_url: 'https://telxius.com/'
            logo: telxius.svg
            crunchbase: 'https://www.crunchbase.com/organization/telxius'
