### ISSUE TITLE
Add Vertiv to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#199]
Add logo and metadata for Vertiv

**Comment by wesreisz** [comment]
Category: OEM  (https://www.vertiv.com/globalassets/documents/infographics/vertiv-ig-en-gl-fact_sheet_final_103563_06.pdf)
crunchbase: https://www.crunchbase.com/organization/vertiv
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Vertiv_logo.svg/1024px-Vertiv_logo.svg.png

**Comment by wesreisz** [comment]
Done
