### ISSUE TITLE
Add XILINX to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#208]
Add logo and metadata for XILINX

**Comment by bprestonlf** [comment]
https://drive.google.com/open?id=15AuAxOYGv-C-gsdLkoG_mFu4xfLlOI4P

**Comment by bprestonlf** [comment]
SVG Option 2: https://drive.google.com/open?id=1mXxoOCiBSiGwB-p9E-PDpPq-ITFLVpNB

**Comment by wesreisz** [comment]
uploaded
