### ISSUE TITLE
Add ZTE to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#213]
Add logo and metadata for ZTE

**Comment by ninjaginja** [comment]
svg logo found here: https://cdn.shopify.com/s/files/1/1742/1195/t/4/assets/globomenu24681528559524.svg

**Comment by dankohn** [comment]
Note that that is an out of date logo. Best place to find logos is to start with https://landscape.cncf.io/format=card-mode&grouping=no

**Comment by ninjaginja** [comment]
Thanks @dankohn . Will use this one instead - https://landscape.cncf.io/logos/zte-kcsp.svg
