### ISSUE TITLE
Add Fledge to the Landscape

### ISSUE THREAD

**Issue by wesreisz** [lf-edge-landscape/lfedge-landscape#263]
Fledge 
Crunchbase: N/a 
Landscape Section Placement: Platform / IoT 
Logo: File Attached 

[fledge-horizontal-color.svg.zip](https://github.com/lf-edge-landscape/lfedge-landscape/files/3893844/fledge-horizontal-color.svg.zip)

**Comment by wesreisz** [comment]
Quick search didn't find the repo and no crunchbase. Followed up email request with repo and crunchbase to add.

**Comment by bprestonlf** [comment]
https://github.com/fledge-iot/fledge

**Comment by wesreisz** [comment]
Stage: LF Edge Incubating

**Comment by bprestonlf** [comment]
Clarification: Stage is LF Edge At Large 

https://wiki.lfedge.org/display/LE/Stage+1%3A+At+Large
