### ISSUE TITLE
Add Baetyl to Landscape

### ISSUE THREAD

**Issue by bprestonlf** [lf-edge-landscape/lfedge-landscape#285]
Stage: LF Edge At Large Project (ref https://wiki.lfedge.org/display/LE/Stage+1%3A+At+Large)

Logo: https://github.com/lf-edge/artwork/blob/master/baetyl/horizontal/color/baetyl_horizontal-color.svg

GitHub: https://github.com/baetyl/baetyl

Needs Crunchbase entry created

**Comment by wesreisz** [comment]
Done
