### ISSUE TITLE
Add AWS to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [lf-edge-landscape/lfedge-landscape#91]
Add logo and metadata for AWS

**Comment by bprestonlf** [comment]
https://landscape.cncf.io/logos/amazon-web-services-member.svg

Full entry to leverage for PR (website, Crunchbase) = https://landscape.cncf.io/format=card-mode&grouping=no&selected=amazon-web-services-member

**Comment by ninjaginja** [comment]
added to landscape
